title: Default Page

columns:
  - width: 2/3
    fields:
      text:
        label: Description
        type: textarea
        size: small
  - width: 1/3
    fields:
      lifeCycleIsActive:
        type: toggle
        label: Activer un champs de durée de vie?
        default: false
        text:
          - "non"
          - "oui"
  - width: 3/3
    fields:
      item:
        label: Section
        extends: fields/itemSection

