title: Default Page

columns:
  - width: 3/3
    fields:
      text:
        label: Description
        type: textarea
        size: small
  - width: 3/3
    fields:
      item:
        label: Section
        extends: fields/itemSection

